### ISSUE TITLE
afksys: Player:AFKTime() returns improper values

### ISSUE THREAD

**Issue by Cynosphere** [Re-Dream/misc#31]
Player:AFKTime() returns time since server was online up to the point they were AFK for the server and other players.

Unless I'm doing something completely wrong or missing something like a calculation that should be there in the first place... 🙄

**Comment by Zeni44** [comment]
`Player:AFKTime()` returns the last time the player was present relative to the server uptime (CurTime()) as you said.

If you want to get the time for how long the player has been afk for, use `CurTime() - Player:AFKTime()`.
It doesn't return improper values but rather has a unclear function name.

**Comment by Cynosphere** [comment]
Alright, thanks
